In [9]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
import spglib
from itertools import product

In [58]:
lattice = [[0.0, 0.5, 0.5],
           [0.5, 0.0, 0.5],
           [0.5, 0.5, 0.0]]
lattice = [[-0.5, 0.5, 0.5],
           [0.5, -0.5, 0.5],
           [0.5, 0.5, -0.5]]
positions = [[0.0, 0.0, 0.0]] 
species = [1]
cell = (lattice, positions, species)
print(spglib.get_spacegroup(cell))

Im-3m (229)


- We can easily form all bond vectors, but we want all unique ones....
- bond vectors should be lattice vectors
- non trivial in general to generate all non-equivalent bonding vectors...

In [62]:
def point_matrices(cell,cutoff=0.9):
    
    space_group = spglib.get_symmetry(cell)
    bv=[]
    for t,m in zip(space_group['translations'],space_group['rotations']):
        bv.append(m@cell[0]+t) # np.r_[cell[0]]+
    bv = np.r_[bv].reshape((-1,3))
    bv = bv[np.linalg.norm(bv,axis=1)<cutoff]
    return bv
def bond_vectors(cell,cutoff=0.9):
    C = np.r_[cell[0]]
    tbv=[]
    for ijk in product([-2,-1,0,1,2],repeat=3):
        bv = np.r_[ijk]@C
        l = np.linalg.norm(bv)
        if l>0.0 and l<cutoff:
            tbv.append(bv)
    
    return np.r_[tbv]
    

In [67]:
B = bond_vectors(cell,cutoff=1.1)
mag = np.linalg.norm(B,axis=1)
mags = np.unique(mag)

print(B[mag==mags[0]])
print("----")
print(B[mag==mags[1]])

[[-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5]
 [-0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]
----
[[ 0.  0. -1.]
 [ 0. -1.  0.]
 [-1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
print([m@np.r_[[0.0,0.5,0.5]] for m in point_matrices(cell)])

[0.5, 0.25, 0.25, -0.5, -0.25, -0.25, -0.25, -0.5, 0.25, 0.5, 0.25, 0.5, -0.25, -0.5, -0.25, -0.25, 0.25, 0.25, 0.25, 0.25, -0.25, -0.25, -0.25, -0.5, -0.25, 0.25, 0.5, 0.25, 0.25, 0.5, -0.25, -0.5, -0.5, -0.25, 0.5, 0.25, 0.25, 0.5, 0.25, -0.25, -0.5, -0.25, -0.5, -0.25, 0.5, 0.25, 0.25, 0.5, -0.25, -0.5, -0.25, -0.25, 0.25, 0.25, 0.25, 0.25, -0.25, -0.25, -0.25, -0.25, -0.5, 0.25, 0.25, 0.5, 0.5, 0.25, -0.5, -0.25, -0.5, -0.25, 0.5, 0.25, 0.25, 0.25, 0.5, -0.25, -0.25, -0.5, -0.25, -0.5, 0.25, 0.5, 0.5, 0.25, -0.5, -0.25, -0.25, -0.25, 0.25, 0.25, 0.25, 0.25, -0.25, -0.25, -0.5, -0.25, -0.25, 0.5, 0.25, 0.25, 0.5, 0.25, -0.5, -0.25, -0.25, -0.5, 0.25, 0.5]


In [7]:
M = point_matrices(cell,bond_vectors)
b = np.r_[[0.5,0.5,0.0]]
print(np.unique([m@b for m in M],axis=0))

# generate one set then see if others fill it. Reasonable for users to pick which bonding vectors they want, we can do the rest....


TypeError: '<' not supported between instances of 'float' and 'function'

In [ ]:
bv = bond_vectors(cell,cutoff=0.5*(1.0+1.0/np.sqrt(2.0)))
print(bv[bv.sum(axis=1).argmax()])

In [ ]:
space_group = spglib.get_symmetry(cell)#tuple([cell[0],cell[1],cell[2]]))
print(space_group['translations'])
